### ISSUE TITLE
Mauvaise affiliation

### ISSUE THREAD

**Issue by jg-you** [laurenthebertdufresne/laurenthebertdufresne.github.io#1]
Pas Professeur

**Comment by louisroy** [comment]
Toi même.

**Comment by jg-you** [comment]
Bro! Ça ce dit pas.

**Comment by louisroy** [comment]
YOU'VE BEEN SCHOLARED :facepunch:

**Comment by louisroy** [comment]
@jg-you faudrait bin que tu fermes ce ticket-là un jour.

**Comment by jg-you** [comment]
![image](https://user-images.githubusercontent.com/6925003/34389066-6ac59ba0-eb05-11e7-80d2-e10256816ed9.png)

**Comment by jg-you** [comment]
Réglé dans le commit https://github.com/laurenthebertdufresne/laurenthebertdufresne.github.io/commit/0e3a225790771843fefe4266ce4fdc6ef70118f9

**Comment by louisroy** [comment]
👌 best screenshot

**Comment by LaurentHebert** [comment]
Hahaha quessé ço
